---
title: "S1 (Fall): Introduction"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

For the first semester (S1 Fall), there are 10 topics for four modules in this R training. For each topic, we have compiled different online materials for you to go through, as well as assignments for you to test your skills. This program is largely based on the great online tutorials from RStudio called [Primers](https://rstudio.cloud/learn/primers). This training is a self-guided learning, which allows you to engage with the material at your own pace and at times that suit you the most. These topics will help you acquire basic skills in R, which will be most useful in the upcoming CDS Hackathons. 

Each session takes around 1-2 hours. The deadline to complete all sessions is by XXX, where you will have a meeting with our CDS team members to review and discuss your progress. For any questions, please write to our PhD student [Yunrui Liu](https://psychologie.unibas.ch/en/persons/liu-yunrui/). 



::: l-body
| # | Module     | Topic                         |
|---| ---------|-------------------------------|
| 1 | The Basics | [Getting Started](session1.html) |
| 2 | The Basics | [Visualization Basics](session2.html) |
| 3 | The Basics | [Programming Basics](session3.html) ||
| 4 | Work with Data | [Working with Tibbles/Isolating Data with dplyr](session4.html) |
| 5 | Work with Data | [Derive Information with dplyr](session5.html) |
| 6 | Visualize Data | [Exploratory Data Analysis](session6.html) |
| 7 | Visualize Data | [Charts and Plots](session7.html) |
| 8 | Tidy your Data | [Reshape Data](session8.html) |
| 9 | Tidy your Data | [Separate and Unite Columns](session9.html) |
| 10 | Tidy your Data | [Join Data Sets](session10.html) |
| 11 | Review | [Review and Meeting with CDS Team](session11.html) |

:::